"""change restaurant address to json

Revision ID: 646504b4f31c
Revises: a121e97bae42
Create Date: 2026-09-16 01:39:02.233485

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '646504b4f31c'
down_revision: Union[str, Sequence[str], None] = 'a121e97bae42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('restaurants', 'address',
           existing_type=sa.VARCHAR(),
           type_=sa.JSON(),
           existing_nullable=False,
           postgresql_using='address::json')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('restaurants', 'address',
               existing_type=sa.JSON(),
               type_=sa.VARCHAR(),
               existing_nullable=False)
    # ### end Alembic commands ###
