"""add portions to menu items

Revision ID: cbc730cff7eb
Revises: 60ff76ba8d36
Create Date: 2026-09-24 15:04:39.604273

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cbc730cff7eb'
down_revision: Union[str, Sequence[str], None] = '60ff76ba8d36'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menu_items', sa.Column('portions', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('menu_items', 'portions')
    # ### end Alembic commands ###
